McCLIM 笔记

* 1. CLIM 的示例:
  > (clim-demo::demodemo)

  下面的是其中的一个
  > (clim-demo::run-test 'clim-demo::address-book)

* 2. CLIM 的顶层 Listener
  > (require :clim-listener)
  > (clim-listener:run-listener)
  此顶层可以看作一个功能不完全的 IDE.



** (I) 使用 mcclim.asd 安装
  1. 创建到 mcclim.asd 的符号链接
    for SBCL, it's
    ln -sf /path/to/mcclim.asd ~/.sbcl/systems/
    如果没有 ~/.sbcl/systems/ 目录, 则创建

    for CCL, it's
    ln -sf /path/to/mcclim.asd ~/.ccl/systems/

    Load McCLIM from Lisp's REPL:
    (asdf:oos 'asdf:load-op :mcclim)

    Reference: McCLIM-master/INSTALL


** (II) 使用 Quicklisp 安装:
; SLIME 2015-08-24
CL-USER> (ql:quickload :mcclim)
To load "mcclim":
  Install 5 Quicklisp releases:
    clx flexichain mcclim slime spatial-trees
; Fetching #<URL "http://beta.quicklisp.org/archive/clx/2015-08-04/clx-20150804-git.tgz">
; 444.35KB
==================================================
455,011 bytes in 5.82 seconds (76.30KB/sec)
; Fetching #<URL "http://beta.quicklisp.org/archive/slime/2015-07-09/slime-2.14.tgz">
; 1044.71KB
==================================================
1,069,784 bytes in 12.64 seconds (82.63KB/sec)
; Fetching #<URL "http://beta.quicklisp.org/archive/spatial-trees/2014-08-26/spatial-trees-20140826-git.tgz">
; 21.41KB
==================================================
21,925 bytes in 0.20 seconds (109.24KB/sec)
; Fetching #<URL "http://beta.quicklisp.org/archive/flexichain/2010-10-06/flexichain_1.5.1.tgz">
; 19.45KB
==================================================
19,919 bytes in 0.22 seconds (86.84KB/sec)
; Fetching #<URL "http://beta.quicklisp.org/archive/mcclim/2015-10-31/mcclim-20151031-git.tgz">
; 2098.85KB
==================================================
2,149,222 bytes in 69.02 seconds (30.41KB/sec)
; Loading "mcclim"
...
;; (DEFCLASS) is patched.
;; (DEFCONSTANT) is patched.
;; (INTERACTIVE-STREAM-P) is patched................................................
[package clim-lisp]...............................
[package clim]....................................
[package clim-sys]................................
[package clim-extensions].........................
[package clim-backend]............................
[package clim-internals]..........................
[package clim-demo]...............................
[package clim-user]...............................
[package goatee]..................................
[package clim-ffi]................................
[package clim-tab-layout].........................
[package spatial-trees]...........................
[package spatial-trees-protocol]..................
[package rectangles]..............................
[package spatial-trees-impl]......................
[package flexichain]..............................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
[package clim-postscript].........................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
[package esa-utils]...............................
[package esa].....................................
[package esa-buffer]..............................
[package esa-io]..................................
..................................................
[package eqv-hash]................................
[package automaton]...............................
[package binseq]..................................
[package drei-buffer].............................
[package drei-undo]...............................
[package drei-kill-ring]..........................
[package drei-base]...............................
[package drei-abbrev].............................
[package drei-syntax].............................
[package drei]....................................
[package drei-motion].............................
[package drei-editing]............................
[package drei-core]...............................
[package drei-fundamental-syntax].................
[package drei-lr-syntax]..........................
[package drei-lisp-syntax]........................
[package drei-commands]...........................
[package drei-user]...............................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
[package xlib]....................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
[package glx].....................................
[package gl]......................................
[package dpms]....................................
[package xtest]...................................
[package xlib.xinerama]...........................
[package xclclock]................................
[package clipboard]...............................
[package demos]...................................
[package gl-test].................................
[package xmandel].................................
[package clim-xcommon]............................
[package clim-clx]................................
[package image]...................................
..................................................
[package clim-null]..........................
(:MCCLIM)
CL-USER>


[package spatial-trees]...........................
[package spatial-trees-protocol]..................
[package rectangles]..............................
[package spatial-trees-impl]......................
[package flexichain]..............................
[package clim-postscript].........................
[package esa-utils]...............................
[package esa].....................................
[package esa-buffer]..............................
[package esa-io]..................................
[package eqv-hash]................................
[package automaton]...............................
[package binseq]..................................
[package drei-buffer].............................
[package drei-undo]...............................
[package drei-kill-ring]..........................
[package drei-base]...............................
[package drei-abbrev].............................
[package drei-syntax].............................
[package drei]....................................
[package drei-motion].............................
[package drei-editing]............................
[package drei-core]...............................
[package drei-fundamental-syntax].................
[package drei-lr-syntax]..........................
[package drei-lisp-syntax]........................
[package drei-commands]...........................
[package drei-user]...............................
[package xlib]....................................
[package glx].....................................
[package gl]......................................
[package dpms]....................................
[package xtest]...................................
[package xlib.xinerama]...........................
[package xclclock]................................
[package clipboard]...............................
[package demos]...................................
[package gl-test].................................
[package xmandel].................................
[package clim-xcommon]............................
[package clim-clx]................................
[package image]...................................
[package clim-null]...............................


* 3. 依赖的库的简介

** spatial-trees
-------------
spatial-trees is a set of dynamic index data structures for spatially-extended data.
The flavors provided are, as of the 0.1 release (on 2004-12-03):
	* R-trees, as in R-TREES: A DYNAMIC INDEX STRUCTURE FOR SPATIAL SEARCHING, Antonin
	  Guttman, Proc. ACM SIGMOD Int. Conf. on Management of Data, 1984.
	* Greene-trees, as in An Implementation and Performance Analysis of Spatial Data
	  Access Methods, Diane Greene, Proc. 5th IEEE Int. Conf. on Data Engineering, 1989.
    * R*-trees, as in The R*-tree: An Efficient and Robust Access Method for Points and
	  Rectangles, Beckmann, Kriegel, Schneider and Seeger, Proc. ACM Int. Conf. on
	  Management of Data, 1990
	* X-trees, as in The X-tree: An Index Structure for High-Dimensional Data, Berchtold,
	  Keim and Kriegel, Proc. 22th Int. Conf. on Very Large Databases, 1996
    Future work planned includes performance enhancements, incorporation of more index
structures, and some work on supporting more optimal indexing when the entire set of data
is known at index creation time; for more details, see the TODO file in the binary
distribution.
    The code is licensed BSD-style, and is intended to be similar in spirit to Nathan Froyd's
TREES Library.
You can get this via Quicklisp.
http://cliki.net/spatial-trees



** spatial-trees-impl				#impl 接口实现
------------------

flexichain
Flexichain is an API for editable sequences. Its primary use is in end-user applications
that edit sequences of objects such as text editors (characters), word processors (characters,
paragraphs, sections, etc), score editors (notes, clusters, measures, etc), though it can also
be used as a stack and a double-ended queue.



** esa
---
    ESA is a layer atop CLIM functionality to provide an Emacs-Style Application framework.
Currently, it provides support for a top-level application loop, commands including
numeric arguments, nested command tables (for key sequences), keyboard macros, buffer
management, filesystem interaction, and support for self-documenting applications. It
was developed initially for Climacs, a Common Lisp Emacs, but other McCLIM applications
such as Gsharp and a CLIM file manager also use portions of its functionality.



** drei
----


** image
-----
	Image is an image-drawing with a few drawing primitives (circles, ellipses, lines,
rectangles, text). It currently has code for "dumping" an image to either X11 drawables
or GIF files (via Skippy). It currently only has a single font available for drawing
text, but it should be possible to extend the font handling to load fonts from other
formats.

