C++ Note

* 1. cpp/c 中的兼容性问题
  在 gcc 默认一个未初始化的指针为 NULL, VC++6.0 中并不默认为 NULL, 所以有可能会导致不兼容
  解决方法: 比如说构建链表, 一个节点的指针域最好都初始化为 NULL.
   
* 2. 判断输入的内容是否符合预期
  当 cin.fail() == true 时, 说明输入的内容不符合预期
  e.g. 
      int e;
      cin >> e;
        
      如果输入的值的类型为 int 类型, 那么 cin.fail() == false;
      否则 cin.fail() == true.

* 3. stl

vector(向量): C++中的一种数据结构,确切的说是一个类.它相当于一个动态的数组,当程序员无法知道自己需要的数组的规模多大时,用其来解决问题可以达到最大节约空间的目的.

它是一个多功能的，能够操作多种数据结构和算法的模板类和函数库。vector之所以被认为是一个容器，是因为它能够像容器一样存放各种类型的对象，简单地说，vector是一个能够存放任意类型的动态数组，能够增加和压缩数据。使用vector库，必须在文件首#include<vector>


常用函数：

1.push_back          在数组的最后添加一个数据

2.pop_back           去掉数组的最后一个数据
3.at                 得到编号位置的数据
4.begin              得到数组头的指针
5.end                得到数组的最后一个单元+1的指针
6.front              得到数组头的引用
7.back               得到数组的最后一个单元的引用
8.max_size           得到vector最大可以是多大
9.capacity           当前vector分配的大小
10.size            当前使用数据的大小
11.resize          改变当前使用数据的大小，如果它比当前使用的大，者填充默认值
12.reserve       改变当前vecotr所分配空间的大小
13.erase          删除指针指向的数据项
14.clear           清空当前的vector
15.rbegin         将vector反转后的开始指针返回(其实就是原来的end-1)
16.rend           将vector反转构的结束指针返回(其实就是原来的begin-1)
17.empty         判断vector是否为空
18.swap          与另一个vector交换数据

-- http://blog.sciencenet.cn/blog-798373-861618.html

sort 包含在 algorithm 中, 故 #include <algorithm>
OpenCV 的命名空间 cv(using namespace cv;) 中也导出了 sort 方法.
arr1 为 vector 的一个实例, 则
sort( arr1.begin(), arr1.end() );
会按升序将数组 arr1 全部排列.
* 4. string 类
** std::string 转 const string
#+BEGIN_SRC cpp
string name = "blablabla";
const char* constName;
constName = name.c_str();
#+END_SRC
** const string 转 std::string
#+BEGIN_SRC cpp
string str = string(const char *s);    //用c字符串s初始化
#+END_SRC
例:
#+BEGIN_SRC cpp
const char* s = "abcd";    // same as {const char* s = "abcd\0"}
string str = string(s);
#+END_SRC
** 数字转 std::string
#+BEGIN_SRC cpp
#include <sstream>

for(int i = 0; i < 3; i++)
{
    stringstream ss;
    ss << i;
    string name;
    ss >> name;
    name += ".txt";
    cout << name << endl;
}
#+END_SRC
* 5. error: variable ‘std::ifstreamxxx'’ has initializer but incomplete ty
没有加头文件 #include <fstream>
