Linux Note

* 1. 更改文件(夹)所有者
   $ chown user_name pass.html # 更改文件所有者, 将 pass.html 的所有者
   设置为 user_name $ chown -R user_name quicklisp # 加入 -R 参数, 递
   归地将 quicklisp 目录下的所有文件的所有者设置为 user_name

* 2. 为 UUID = *** 准备的磁盘尚未就绪或不存在

   For Example:由于安装其他系统时误格了此 OS 的 swap 分区, 导致分区
       （磁盘）UUID改变．报如下错误: "为
       UUID=9da69d61-8dd1-4bab-9330-9e7e288309b3 准备的磁盘尚未就绪或
       不存在"

	   (1) 查看挂载脚本中的老的UUID当前挂载脚本中的dev设备及UUID:

	   $ cat /etc/fstab

	   # /etc/fstab: static file system information.
	   #
	   # Use 'blkid' to print the universally unique identifier for a
	   # device; this may be used with UUID= as a more robust way to name devices
	   # that works even if disks are added and removed. See fstab(5).
	   #
	   # <file system> <mount point>   <type>  <options>       <dump>  <pass>
	   # / was on /dev/sda10 during installation
	   UUID=492b6b13-75d5-4d67-9f73-2df2b989ac3b / ext4
	   errors=remount-ro 0 1
	   # /boot/efi was on /dev/sda1 during installation
	   UUID=2C37-128C /boot/efi vfat defaults 0 1
	   # swap was on /dev/sda9 during installation
	   UUID=9da69d61-8dd1-4bab-9330-9e7e288309b3 none swap sw 0 0

	   (2)查看当前磁盘（分区）的UUID

	   $ blkid /dev/sda1: UUID="2C37-128C" TYPE="vfat" /dev/sda2:
	   UUID="E7D8-37D5" TYPE="vfat" /dev/sda4: LABEL="Reserve"
	   UUID="0000678400004823" TYPE="ntfs" /dev/sda5:
	   LABEL="Files" UUID="00041362000DEECC" TYPE="ntfs"
	   /dev/sda6: LABEL="forOS"
	   UUID="7380c2f6-3ffe-47eb-93f3-2f55af1a743f" TYPE="ext4"
	   /dev/sda7: LABEL="Data" UUID="000B7FDA0001E7A1" TYPE="ntfs"
	   /dev/sda8: LABEL="Storage" UUID="5EF31040246470A2"
	   TYPE="ntfs" /dev/sda9:
	   UUID="17da422b-5fa1-4d49-a8f4-a413f39db691" TYPE="swap"
	   /dev/sda10: UUID="492b6b13-75d5-4d67-9f73-2df2b989ac3b"
	   TYPE="ext4" /dev/sda11:
	   UUID="54ddf013-3f91-474f-9f6a-7d368716a4b0" TYPE="swap"
	   /dev/sda12: UUID="43bba5f1-fbaf-4b97-a153-267dd39f7534"
	   TYPE="ext4"

	   可见: 当前 sda9 的 UUID 与原 fstab 挂载脚本中的 UUID 不符.


	   (3)修改fstab挂在脚本

	   $ sudo gedit /etc/stab

	   将 sda9 的 UUID 更改

* 3. gst
	问题描述: gst(gnu-smalltalk) 在 bash 下可以正常调用($ gst
		RTN), 但是在 zsh 下,普通方式调用会报如下错误: fatal:
		Not a git repository (or any of the parent
		directories): .git但是如果加上 sudo 则可以调用

	错误原因:未知

	解决方法:在 .zshrc 中配置别名如下alias
		gst="/usr/local/bin/gst"即将 gst 作为程序调用的路径的
		别名, 重新打开 zsh 即生效

* 4. chrome 安装问题
	问题描述: Debian 下安装 Chrome, 如果 sudo dpkg -i
		google-chrome**.deb 安装出错

	错误原因:可能是由于没有先升级系统

	解决方法: sudo apt-get update sudo apt-get upgrade然后执行
		sudo apt-get -f install则 chrome 安装成功

* 5. 挂载/卸载 U 盘

   查看文件系统: $ df -ah文件系统 容量 已用 可用 已用% 挂载
   点...........................................................
   /dev/sdc1 15G 14G 1.4G 91% /media/user_name/0AC6-ACA6 #所要挂载的 U
   盘

   挂载: $ mkdir /tmp/udisk $ sudo mount /dev/sdc1 /tmp/udisk

   卸载$ sudo umount /dev/sdc1

* 6. 在 GUI 与 CLI 之间切换
   切换到 CLI: C-M-F[1~6]切换到 GUI: C-M-F7

* 7. lsblk 可以查看所有的分区
   $ lsblk NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINT sda 8:0 0 465.8G 0
   disk ├─sda1 8:1 0 128M 0 part ├─sda2 8:2 0 128M 0 part ├─sda3
   8:3 0 56G 0 part / ├─sda4 8:4 0 60G 0 part ├─sda5 8:5 0 60G 0
   part /mediuser_name/Files ├─sda6 8:6 0 39.1G 0 part
   /mediuser_name/forOS ├─sda7 8:7 0 54.1G 0 part ├─sda8 8:8 0
   300M 0 part ├─sda9 8:9 0 100M 0 part /boot/efi └─sda10 8:10 0
   188.4G 0 part sr0 11:0 1 1024M 0 rom sr1 11:1 1 1024M 0 rom

* 8. 显示系统中所有的字体
   $ fc-list一般系统中的字体存放在 /usr/share/fonts 目录下$ ls
   /usr/share/fonts cmap opentype truetype type1 X11向系统中加入字体只
   需将字体拷贝到此目录中即可

* 9. 列出系统的头文件
   $ echo "" | g++ -v -x c++ -E -会找到类似下面的这些行#include "..."
   search starts here: #include <...> search starts here:
   /usr/include/c++/4.9 /usr/include/x86_64-linux-gnu/c++/4.9
   /usr/include/c++/4.9/backward
   /usr/lib/gcc/x86_64-linux-gnu/4.9/include /usr/local/include
   /usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed
   /usr/include/x86_64-linux-gnu /usr/include End of search list.

   中间的部分即为所需

* 10. wget

如要下载 http://norvig.com/paip/ 目录下的所有文件, 应输入如下命令
# paip后的 / 不可省，否则被下载的则是页面 paip
$ wget -r -np -nH -L norvig.com/paip/

http://www.cnblogs.com/lidp/archive/2010/03/02/1696447.html

wget 下载整个网站，或者特定目录需要下载某个目录下面的所有文件。命令如下

wget -c -r -np -k -L -p www.xxx.org/pub/path/

在下载时。有用到外部域名的图片或连接。如果需要同时下载就要用-H参数。

wget -np -nH -r --span-hosts www.xxx.org/pub/path/

-c 断点续传r 递归下载，下载指定网页某一目录下（包括子目录）的所有文件
-nd 递归下载时不创建一层一层的目录，把所有的文件下载到当前目录np 递归
-下载时不搜索上层目录，如wget -c -r www.xxx.org/pub/path/没有加参数-np，
-就会同时下载path的上一级目录pub下的其它文件k 将绝对链接转为相对链接，
-下载整个站点后脱机浏览网页，最好加上这个参数L 递归时不进入其它主机，
-如wget -c -r www.xxx.org/如果网站内有一个这样的链接：www.yyy.org，不
-加参数-L，就会像大火烧山一样，会递归下载www.yyy.org网站p 下载网页所需
-的所有文件，如图片等A 指定要下载的文件样式列表，多个样式用逗号分隔i
-后面跟一个文件，文件内指明要下载的URL

还有其他的用法，我从网上搜索的，也一并写上来，方便以后自己使用。

wget的常见用法

wget的使用格式Usage: wget [OPTION]… [URL]…

** 用wget做站点镜像:
wget -r -p -np -k http://dsec.pku.edu.cn/~usr_name/
# 或者
wget -m http://www.tldp.org/LDP/abs/html/


** 在不稳定的网络上下载一个部分下载的文件，以及在空闲时段下载
wget -t 0 -w 31 -c http://dsec.pku.edu.cn/BBC.avi -o down.log &
# 或者从filelist读入要下载的文件列表
wget -t 0 -w 31 -c -B ftp://dsec.pku.edu.cn/linuxsoft -i filelist.txt
-o down.log &

上面的代码还可以用来在网络比较空闲的时段进行下载。我的用法是:在mozilla
中将不方便当时下载的URL链接拷贝到内存中然后粘贴到文件filelist.txt中，
在晚上要出去系统前执行上面代码的第二条。


** 使用代理下载
wget -Y on -p -k https://sourceforge.net/projects/wvware/

代理可以在环境变量或wgetrc文件中设定

# 在环境变量中设定代理
export PROXY=http://211.90.168.94:8080/
# 在~/.wgetrc中设定代理
http_proxy = http://proxy.yoyodyne.com:18023/ ftp_proxy =
http://proxy.yoyodyne.com:18023/

wget各种选项分类列表


** 启动

-V, –version 显示wget的版本后退出h, –help 打印语法帮助b, –background
-启动后转入后台执行e, –execute=COMMAND执行`.wgetrc'格式的命令，wgetrc
-格式参见/etc/wgetrc或~/.wgetrc


** 记录和输入文件

-o, –output-file=FILE 把记录写到FILE文件中a, –append-output=FILE 把记
-录追加到FILE文件中d, –debug 打印调试输出q, –quiet 安静模式(没有输出)
-v, –verbose 冗长模式(这是缺省设置) nv, –non-verbose 关掉冗长模式，但
-不是安静模式i, –input-file=FILE 下载在FILE文件中出现的URLs F,
-–force-html 把输入文件当作HTML格式文件对待B, –base=URL 将URL作为在-F
--i参数指定的文件中出现的相对链接的前缀–sslcertfile=FILE 可选客户端证
-书–sslcertkey=KEYFILE 可选客户端证书的KEYFILE –egd-file=FILE 指定EGD
-socket的文件名


** 下载

–bind-address=ADDRESS指定本地使用地址(主机名或IP，当本地有多个IP或名字
时使用) -t, –tries=NUMBER 设定最大尝试链接次数(0 表示无限制).  -O
–output-document=FILE 把文档写到FILE文件中-nc, –no-clobber 不要覆盖存
在的文件或使用.#前缀-c, –continue 接着下载没下载完的文件–progress=TYPE
设定进程条标记-N, –timestamping 不要重新下载文件除非比本地文件新-S,
–server-response 打印服务器的回应–spider 不下载任何东西-T,
–timeout=SECONDS 设定响应超时的秒数-w, –wait=SECONDS 两次尝试之间间隔
SECONDS秒–waitretry=SECONDS 在重新链接之间等待1…SECONDS秒–random-wait
在下载之间等待0…2*WAIT秒-Y, –proxy=on/off 打开或关闭代理-Q,
–quota=NUMBER 设置下载的容量限制–limit-rate=RATE 限定下载输率


** 目录

-nd –no-directories 不创建目录x, –force-directories 强制创建目录nH,
-–no-host-directories 不创建主机目录P, –directory-prefix=PREFIX 将文件
-保存到目录 PREFIX/… –cut-dirs=NUMBER 忽略 NUMBER层远程目录


** HTTP 选项

–http-user=USER 设定HTTP用户名为 USER.  http-passwd=PASS 设定http密码
–为 PASS.  -C, –cache=on/off 允许/不允许服务器端的数据缓存 (一般情况下
–允许).  -E, –html-extension 将所有text/html文档以.html扩展名保存
–ignore-length 忽略 `Content-Length'头域header=STRING 在headers中插入
–字符串 STRING proxy-user=USER 设定代理的用户名为 USER
–proxy-passwd=PASS 设定代理的密码为 PASS referer=URL 在HTTP请求中包含
–`Referer: URL'头-s, –save-headers 保存HTTP头到文件-U,
––user-agent=AGENT 设定代理的名称为 AGENT而不是 Wget/VERSION.
–no-http-keep-alive 关闭 HTTP活动链接 (永远链接).  cookies=off 不使用
–cookies.  load-cookies=FILE 在开始会话前从文件 FILE中加载cookie
–save-cookies=FILE 在会话结束后将 cookies保存到 FILE文件中


** FTP 选项

-nr, –dont-remove-listing 不移走 `.listing'文件g, –glob=on/off 打开或
-关闭文件名的 globbing机制–passive-ftp 使用被动传输模式 (缺省值).
-–active-ftp 使用主动传输模式–retr-symlinks 在递归的时候，将链接指向文
-件(而不是目录)


** 递归下载

-r, –recursive 递归下载－－慎用!  l, –level=NUMBER 最大递归深度 (inf
-或 0 代表无穷).  –delete-after 在现在完毕后局部删除文件k,
-–convert-links 转换非相对链接为相对链接K, –backup-converted 在转换文
-件X之前，将之备份为 X.orig m, –mirror 等价于 -r -N -l inf -nr.  p,
-–page-requisites 下载显示HTML文件的所有图片


** 递归下载中的包含和不包含(accept/reject)

-A, –accept=LIST 分号分隔的被接受扩展名的列表R, –reject=LIST 分号分隔
-的不被接受的扩展名的列表D, –domains=LIST 分号分隔的被接受域的列
-表–exclude-domains=LIST 分号分隔的不被接受的域的列表–follow-ftp 跟踪
-HTML文档中的FTP链接–follow-tags=LIST 分号分隔的被跟踪的HTML标签的列表
-G, –ignore-tags=LIST 分号分隔的被忽略的HTML标签的列表H, –span-hosts
-当递归时转到外部主机L, –relative 仅仅跟踪相对链接I,
-–include-directories=LIST 允许目录的列表X, –exclude-directories=LIST
-不被包含目录的列表np, –no-parent 不要追溯到父目录

* 11. 语言环境配置
  $ sudo dpkg-reconfigure locales选中 [X] en_US.UTF-8 UTF-8 [X]
  zh_CN.GB18030 GB18030 [X] zh_CN.UTF-8 UTF-8参考
  http://cs2.swfc.edu.cn/~wx672/lecture_notes/linux/install.html

* 12. 文件管理器
  Gnome 默认的文件管理器为 Nautilus (鹦鹉螺)
* 13. 拨号上网
1. 安装 pppoe 和 pppoeconf
   $ sudo apt-get install pppoe $ sudo apt-get install pppoeconf
2. 设置
   $ sudo pppoeconf按照提示进行设置, 输入用户名和密码
3. 重启
4. 常用命令
   $ sudo pon dsl-provider #启用$ sudo poff (dsl...)  #停用
* 14. 软件包
1. 安装
2. 卸载
3. 其他
   在 Debian 下, 用户所安装的软件包都在目录 /var/cache/apt/archives 下
有保存,如果用户不清理占用空间就会越来越大. 其子目录 partial 下存放着残
缺的安装包.
* 15. 查看目录所占空间的大小
du dirname可以查看目录 dirname 下的各个文件的大小-h 参数可以以 Human
Readable 的形式输出-s 参数只统计总和, 不以各个单独文件的大小的形式输出
* 16. 挂载磁盘
** 以只读方式挂载磁盘
   $ mount -o ro,auto /dev/sdax /tmp/xxx
** 以755权限自动挂载磁盘
   https://ubuntuforums.org/showthread.php?t=2176441
   修改 /etc/fstab 文件
   $ UUID="xxx" /mnt/yyy auto auto,uid=1000,gid=1000,umask=0022 0 0
   umask is actually used as the inverse or the permissions you're looking for. umask=0022 mounts with permissions 0755 or -rwxr-xr-x
   umask = 0000 时, 挂载后的权限是777, 会导致挂载目录下的文件目录名和背景变为绿色不易识别

* 17. 插入网线, network-manager 提示"线缆已拔出“, ”设备未托管“

1.  修改 '/etc/NetworkManager/NetworkManager.conf', 将 'managed=false'
	修改为 'managed=true'

2.  修改 '/etc/network/interfaces', 添加在文件末尾添加有线网卡配置

	auto eth0 iface eth0 inet dhcp     #the last option decides between dhcp/manul

3.  重启 network-manager 和 networking 服务

    $ sudo service network-manager stop
    $ sudo service networking restart
    $ sudo service network-manager start
* 18. 解决为满足的依赖关系
http://www.voidcn.com/blog/supercooly/article/p-5742609.html
root@ubuntu:/home/chao# apt-get install python-pip
正在读取软件包列表... 完成
正在分析软件包的依赖关系树
正在读取状态信息... 完成
有一些软件包无法被安装。如果您用的是 unstable 发行版，这也许是
因为系统无法达到您要求的状态造成的。该版本中可能会有一些您需要的软件
包尚未被创建或是它们已被从新到(Incoming)目录移出。
下列信息可能会对解决问题有所帮助：

下列软件包有未满足的依赖关系：
 python-pip : 依赖: python-setuptools (>= 0.6c1) 但是它将不会被安装
	      推荐: python-dev-all (>= 2.6) 但无法安装它
E: 无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系。

二、解决办法
步骤一

安装aptitude工具
sudo apt-get install aptitude
步骤二

root@ubuntu:/home/chao# aptitude install python-pip

下列“新”软件包将被安装。
  python-colorama{a} python-distlib{a} python-html5lib{a} python-pip
  python-setuptools{ab}
0 个软件包被升级，新安装 5 个， 0 个将被删除， 同时 0 个将不升级。
需要获取 542 kB 的存档。 解包后将要使用 2,513 kB。
下列软件包存在未满足的依赖关系：
 python-setuptools : 依赖: python-pkg-resources (= 3.3-1ubuntu1) 但是 3.3-1ubuntu2 已安装。
下列动作将解决这些依赖关系：

     保持 下列软件包于其当前版本：
1)     python-pip [未安装的]
2)     python-setuptools [未安装的]

是否接受该解决方案？[Y/n/q/?] n

下列动作将解决这些依赖关系：

     降级 下列软件包：
1)     python-pkg-resources [3.3-1ubuntu2 (now) -> 3.3-1ubuntu1 (trusty)]

是否接受该解决方案？[Y/n/q/?] Y

下列软件包将被“降级”：
  python-pkg-resources
下列“新”软件包将被安装。
  python-colorama{a} python-distlib{a} python-html5lib{a} python-pip
  python-setuptools{a}
0 个软件包被升级，新安装 5 个， 1 个被降级， 0 个将被删除， 同时 0 个将不升级。
需要获取 604 kB 的存档。 解包后将要使用 2,513 kB。

您要继续吗？[Y/n/?] Y
Successful
* 19. Debian Broadcom 无线网卡驱动
Support: Broadcom BCM4311, BCM4312, BCM4313, BCM4321, BCM4322, BCM43224, BCM43225,
BCM43227, BCM43228, BCM43142, BCM4331, BCM4352, BCM4360 devices (wl)

https://wiki.debian.org/wl
** 1.
Add a "non-free" component to /etc/apt/sources.list for your Debian version, for example:

# Debian 8 "Jessie"
deb http://httpredir.debian.org/debian/ jessie main contrib non-free

** 2.
Update the list of available packages. Install the relevant/latest linux-image, linux-headers and broadcom-sta-dkms packages:

# apt-get update
# apt-get install linux-image-$(uname -r|sed 's,[^-]*-[^-]*-,,') linux-headers-$(uname -r|sed 's,[^-]*-[^-]*-,,') broadcom-sta-dkms

** 3.
This will also install the recommended wireless-tools package. DKMS will build the wl module for your system.

Unload conflicting modules:

# modprobe -r b44 b43 b43legacy ssb brcmsmac bcma

** 4.
Load the wl module:

# modprobe wl
* 20. 去除 Network Manager 中的 ifupdown(eth0) 连接
http://askubuntu.com/questions/455736/remove-ifupdowneth0-connection

Open terminal and enable super user mode.

nano /etc/NetworkManager/NetworkManager.conf

The contents of the file will be like this:

[main]
plugins=ifupdown,keyfile,ofono
dns=dnsmasq
[ifupdown]
managed=true

Please change the plugins section to:

plugins=keyfile,ofono

Restart the network manager:

service network-manager restart
* 21. Linux 下游戏闪退
报错:Failed to open BO for returned DRI2 buffer (..*.., dri2 back buffer, named 20).
This is likely a bug in the X Server that will lead to a crash soon.

Reason:
This should be this Intel graphics driver bug: https://bugs.freedesktop.org/show_bug.cgi?id=84372
Solve:
Workaround (from comment #7):
Create a file /etc/X11/xorg.conf.d/20-intel.conf with the following content:
------------------------------------------------------------
Section "Device"
Identifier "Intel Graphics"
Driver "intel"
Option "AccelMethod" "sna"
Option "TearFree" "true"
EndSection
------------------------------------------------------------
... then restart X.
* 22. locate 查找
新安装的软件或库使用 locate 可能找不到, 需要先更新 locate 查找使用的数据库:
$ sudo updatedb
* 23. 内存清理/释放命令
1. 查看内存使用情况
$ free -mh

2. 清理内存
echo 1 > /proc/sys/vm/drop_cache
* 24. tar 解包
How can I extract or uncompress a file from tar ball downloaded from the Internet under Linux using bash command prompt?

You need to use the tar command to extract files from an archive or to create an archive (also known as tarball). A tarball or an archive is nothing but a single file that contains various individual files. It also includes information which allows your to restore files to their original form by one or more extraction programs such as tar command.

Extract or Unpack a TarBall File

To unpack or extract a tar file, type:

tar -xvf file.tar

To save disk space and bandwidth over the network all files are saved using compression program such as gzip or bzip2. To extract / unpack a .tar.gz (gzip) file, enter (note -z option):

tar -xzvf file.tar.gz

To extract / unpack a .tar.bz2 (bzip2) file, enter (note -j option):

tar -xjvf file.tar.bz2

Where,

    -x : Extract a tar ball.
    -v : Verbose output or show progress while extracting files.
    -f : Specify an archive or a tarball filename.
    -j : Decompress and extract the contents of the compressed archive created by bzip2 program (tar.bz2 extension).
    -z : Decompress and extract the contents of the compressed archive created by gzip program (tar.gz extension).

How Do I Extract A Single File Called foo.txt?

To extract a single file called foo.txt, enter:

tar -xvf file.tar foo.txt
tar -xzvf file.tar.gz foo.txt
tar -xjvf file.tar.bz2 foo.txt

You can also specify path such as etc/resolv.conf, enter:

tar -xvf file.tar etc/resolv.conf
tar -xzvf file.tar.gz etc/resolv.conf
tar -xjvf file.tar.bz2 etc/resolv.conf

How Do I Extract a Single Directory Called etc?

To extract a single directory called etc, enter:

tar -xvf file.tar etc
tar -xzvf file.tar.gz etc
tar -xjvf file.tar.bz2 etc

Sample outputs:

etc/
etc/pulse/
etc/pulse/default.pa
etc/pulse/client.conf
etc/pulse/daemon.conf
etc/pulse/system.pa
etc/xml/
etc/xml/docbook-xml.xml.old
etc/xml/xml-core.xml
etc/xml/catalog
etc/xml/catalog.old
etc/xml/docbook-xml.xml
etc/xml/rarian-compat.xml
etc/xml/sgml-data.xml
etc/xml/xml-core.xml.old
etc/xml/sgml-data.xml.old
etc/mail.rc
etc/Wireless/
etc/Wireless/RT2870STA/
etc/Wireless/RT2870STA/RT2870STA.dat
etc/logrotate.conf
etc/compizconfig/
etc/compizconfig/config
.....
...
....
etc/python/
etc/python/debian_config
etc/ConsoleKit/
etc/ConsoleKit/seats.d/
etc/ConsoleKit/seats.d/00-primary.seat
etc/ConsoleKit/run-session.d/
etc/ConsoleKit/run-seat.d/
etc/opt/

From: http://www.cyberciti.biz/faq/tar-extract-linux/
* 25. 字体
Consolas是一种专门为编程人员设计的字体，这一字体的特性是所有字母、数字与符号均能非常容易辨认，而且所有字符都具有相同的宽度，让编人 员看着 更舒服。但我们用Consolas在显示程序源码时，不可避免要使用中文注释。而Consolas不支持中文，因此中文默认是使用宋体显示的。当使用10 点大小的时候，中文就模糊不清了。如果采用斜体显示注释的话，宋体就更加显得支离破碎。

在中文显示上，雅黑字体确实不错，但雅黑不是等宽字体，不能用于源码显示。

使用字体工具将雅黑和Consolas集成在一起后，程序员就可以在Linux环境下的源码中看到优秀的中文显示效果。

具体方案：

先下载雅黑-Consolas混合字体压缩包，资源地址：

http://download.csdn.net/detail/emycslife/4240737

假定下载到~/download/目录下，我们先在这里把压缩包解压，把解压后的字体的ttf文件复制到/usr/share/fonts/的任意目录下：

sudo mkdir -p /usr/share/fonts/vista
sudo cp YaHei.Consolas.1.12.ttf /usr/share/fonts/vista/

更改权限：

sudo chmod 644 /usr/share/fonts/vista/*.ttf

安装字体：

cd /usr/share/fonts/vista/
sudo mkfontscale
sudo mkfontdir
sudo fc-cache -fv

之后我们就可以使用新安装的雅黑-Consolas混合字体字体了。YaHei Consolas Hybrid

From: http://www.cnblogs.com/MonkeyF/archive/2013/05/13/3076466.html
* 26. 查看硬件设备 lspci
查看显卡: lspci -nn | grep '\[03'
(使用 lspci -nn | grep VGA 并不是很恰当, 因为有些显卡命名不是这样的)
* 27. shadowsocks-qt5
openwares.net/linux/debian-shadowsocks-qt5-install.html

* 28. 鼠标移动窗口
You can move a window by pressing

    Alt+F7, then moving it around with the arrow keys, and finish by hitting Return.

    The same goes for resizing, using Alt+F8

You can also press Esc to cancel

Also, while I'm at it:

    Alt+F9 minimises the window

    Alt+F10 maximises it

You can also bring up the application's window menu with Alt+space:
http://askubuntu.com/questions/18243/moving-windows-from-the-keyboard
* 29. pdf 工具
** 1. 合并 pdf
pdfunite file1.pdf file2.pdf out.pdf
pdfunite 是poppler-utils 中的组件, Debian默认已经安装了,但是pdfunite不能合并加密的pdf.
会给出Unimplemented Feature: Could not merge encrypted files ('filename.pdf')
的提示

pdftk file1.pdf file2.pdf cat output out.pdf
pdftk 可以合并加密的pdf.
** 2. 拆分 pdf
extract pages 12-15:
pdftk full-pdf.pdf cat 12-15 output outfile_p12-15.pdf

extract pages 1-10, 15, and 17:
pdftk A=in.pdf cat A1-10 A15 A17 output out.pdf
http://askubuntu.com/questions/221962/how-can-i-extract-a-page-range-a-part-of-a-pdf
* 30. nautilus每次打开的时候始终显示隐藏文件
nautilus每次打开的时候始终显示隐藏文件，但是nautilus的设置中，显示隐藏文件选项是false
这是因为 gtk 的 file-chooser 设置中show-hidden选项为true.
打开dconf系统配置编辑器, 在 org->gtk->settings->file-chooser 中将show-hidden条目的选项更改

open terminal and type:
dconf-editor
Enter and then:
org->gtk->settings->file-chooser
uncheck show-hidden
* 31. Terminal下设置代理
Shadowsocks 服务
** 1 安装proxychains
$ sudo apt-get install proxychains
** 2 编辑配置文件
最后一行改为(这里的1080是shadowsocks中配置的端口号)
socks5 127.0.0.1 1080
** 3 使用
proxychains + 命令
eg.
$ proxychains curl cip.cc
$ sudo proxychains apt-get update
* 32. linux网络有线连接失败“设备未托管” 解决办法
问题描述：

1.Linux 无线网络连接正常，有线网络无法连接

2.ifconfig 命令之后没有eth0 。

3.右上角网络连接处显示有线网络 设备未托管


解决方法：

sudo /etc/NetworkManager/NetworkManager.conf

将managed=false改成true，重启一下就可以了
* 33. 为steam添加其他的分区中的目录作为库文件夹
修改 /etc/fstab 文件，使该分区自动挂载
<file system>                      <mount point>   <type>  <options>       <dump>  <pass>
/dev/disk/by-uuid/0000678400004823 /mnt/Reserve     auto nosuid,nodev,nofail,x-gvfs-show 0 0
* 34. firefox 添加 flashplayer 支持
将 flashplayer 插件 libflashplayer.so 放在 /usr/lib/mozilla/plugins 目录下
* 35. 链接库
使用 pkg-config 可以查看添加链接库时应该使用的名称
如：
$ pkg-config --libs glfw3
glfw
* 36. 软键盘快捷键
C-M-b
* 37. 在众多文件中查找字符串
使用 /cat *.cpp | grep fact/ 虽然也能在文件中查找字符串, 但是搜索完毕后
并不能知道字符串在哪个文件中出现, 而使用 *silver-searcher* 即可解决此问题.
** Install
ubuntu: apt-get install silversearcher-ag
arch:   pacaur -S silver-searcher

** Usage
$ ag fact *.cpp
* 38. 解压缩 .rar
unrar x <myfile>
* 39. Hotspot
$ sudo create_ap wlo1 eno1 voldmore 19960507
如果遇到 RTNETLINK answers: Operation not possible due to RF-kill
的问题(执行 sudo ip link set wlo1 up 也会报这个错):
$ sudo rfkill list all
$ sudo rfkill unblock all
* 40. steamcommunity
Ref:
http://www.3dmgame.com/faq/201712/3707011.html
在 */etc/hosts* 中添加转向ip：
23.52.74.146 steamcommunity.com

* 41. sort
根据第一个字段排序
wc -l * | sort -nk1   # 根据行数将当前目录下的文件排序

* 42. hardware information
查看硬件信息
** cpu
$ lscpu
** memory
$ dmidecode -t memory
** hard disk
$ lsblk
$ fdisk -l
** pci 主板上硬件槽信息
$ lspci
$ lspci -v
$ lspci -vv
$ lspci -t  # 设备树
** BIOS
$ dmidecode -t bios
